---
# tasks file for 1password-secrets
- name: Make sure 1password-cli is installed
  homebrew_cask:
    name: 1password-cli
    state: present

- name: Inject secrets using 1password-cli
  command:
    cmd: op inject -i {{  inventory_dir | dirname }}/templates/{{ secrets_file }}.tpl -o {{  inventory_dir | dirname }}/vars/{{ secrets_file }}
    creates: "{{  inventory_dir | dirname }}/vars/{{ secrets_file }}"
